[package]
name = "audit_trail"
edition = "2024.beta"

[dependencies]
tf_components = { git = "https://github.com/iotaledger/product-core.git", subdir = "components_move", rev = "feat/role-map" }

[addresses]
audit_trail = "0x0"
