[package]
name = "audit_trail"
edition = "2024.beta"

[dependencies]
TfComponents = { git = "https://github.com/iotaledger/product-core.git", subdir = "components_move", rev = "feat/emit-events-for-capabilities" }

[addresses]
audit_trail = "0x0"
