# Copyright (c) 2024 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

[package]
name = "IotaNotarization"
edition = "2024.beta"

[dependencies]
tf_components = { git = "https://github.com/iotaledger/product-core.git", subdir = "components_move", rev = "feat/role-map" }

[addresses]
iota_notarization = "0x0"

[dev-dependencies]

[dev-addresses]
